### ISSUE TITLE
scan flags method fails for empty flag table

### ISSUE THREAD

**Issue by caseyjlaw** [demorest/sdmpy#14]
Reading a realfast cutout sdm with an empty flag table is not working at present.
So for example:
```
sdm = sdmpy.SDM(sdmname)
scan = sdm.scan(scannum)
flags = scan.flags([t0, t1]).all(axis=0)
```

We get an error:

```
src/lxml/objectify.pyx in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/objectify.c:4457)()

src/lxml/objectify.pyx in lxml.objectify._lookupChildOrRaise (src/lxml/objectify.c:7242)()

AttributeError: no such child: row

```

**Comment by demorest** [comment]
This was actually a general problem with trying to iterate over an empty table.  It should now be fixed (in commit dd98bdfd978fc6e253d540eb8fb0cc5981b5dd0b).
