### ISSUE TITLE
dataUID and dataOid

### ISSUE THREAD

**Issue by caseyjlaw** [demorest/sdmpy#5]
In the older sdmpy library, we had a try/except statement to catch a change to the tag used to describe the BDF location. That seems to not work in the with the current lxml-based design. I'm not sure how to fix it, but here's an error for VLA data from 2012:

```
sdm = sdmpy.SDM('12A-336_sb9667618_1b.56040.87127945602')
File "<string>", line unknown
XMLSyntaxError: Element 'dataOid': This element is not expected. Expected is ( dataUID ).
```

Any thoughts on how to fix this?

**Comment by demorest** [comment]
By default the SDM is now checked for validity against the XML schema, but the current schema version does not include dataOid.. You can disable the checking by adding a "use_xsd=False" argument to SDM().  I guess the right way to handle this would be to have the different versions of SDM schema files available and select the right one based on the input file.. sounds like kind of a hassle though..

**Comment by caseyjlaw** [comment]
Ok, I see how that works. However, it seems that scan.py also asks for dataUID explicitly when setting the BDF file name. I see a line like this:

```
self._bdf_fname = os.path.join(bdfdir, uid2fname(sdm['Main'][self.idx].dataUID.EntityRef.get('entityId'))
```

Would it be ok if I add a try/except there?

**Comment by demorest** [comment]
Yeah, sounds good, I think that is the right place to do the try/except.
